# This Dockerfile is mostly for CI, see .github/workflows/tests.yml
FROM rust AS ego-build

WORKDIR /root/build
# Make warnings fatal
ENV RUSTFLAGS="-D warnings"

RUN apt-get update && \
    apt-get install -y libacl1-dev && \
    rm -rf /var/lib/apt/lists/*
RUN rustup component add rustfmt clippy
# Build Cargo dependencies for cache
COPY Cargo.toml Cargo.lock ./
RUN mkdir src/ && \
	echo "pub fn main() {println!(\"dummy function\")}" > src/main.rs && \
	cargo build --bins --tests --color=always && \
	rm -rdv target/*/deps/ego-* \
	        target/*/.fingerprint/ego-*

# Do the actual build
COPY . .
RUN cargo build --bins --tests --color=always
